### ISSUE TITLE
bag error

### ISSUE THREAD

**Issue by QipiaoZhou** [GCaptainNemo/fusion-lidar-camera-ROS#3]
when i run the fuse_node,the terminal tell that
[ERROR] [1655797891.195600078]: Client [/color_pc_node] wants topic /livox/lidar to have datatype/md5sum [sensor_msgs/PointCloud2/1158d486dd51d683ce2f1be655c3c181], but our version has [livox_ros_driver/CustomMsg/e4d6829bdfe657cb6c21a746c86b21a6]. Dropping connection.
how can i fix the problem?

**Comment by GCaptainNemo** [comment]
> when i run the fuse_node,the terminal tell that [ERROR] [1655797891.195600078]: Client [/color_pc_node] wants topic /livox/lidar to have datatype/md5sum [sensor_msgs/PointCloud2/1158d486dd51d683ce2f1be655c3c181], but our version has [livox_ros_driver/CustomMsg/e4d6829bdfe657cb6c21a746c86b21a6]. Dropping connection. how can i fix the problem?

Livox has two data formats: livox_ ros_ Driver/custommsg and sensor_ msgs/PointCloud2. If you use custommsg, you can modify the data format in the code.

**Comment by QipiaoZhou** [comment]
thank you !
