### ISSUE TITLE
yaml file 

### ISSUE THREAD

**Issue by QipiaoZhou** [GCaptainNemo/fusion-lidar-camera-ROS#5]
how to get the yaml file ?by autoware?or what?

**Comment by GCaptainNemo** [comment]
> how to get the yaml file ?by autoware?or what?

Yes, you need to get the external parameters of the lidar through the calibration tool. You can refer to my repository about [lidar-camera-calibration](https://github.com/GCaptainNemo/lidar-camera-calibration)

**Comment by QipiaoZhou** [comment]
thank you for you reply,and i will close the issue.
