### ISSUE TITLE
内外参标定

### ISSUE THREAD

**Issue by mikasazgx** [GCaptainNemo/fusion-lidar-camera-ROS#6]

**Comment by mikasazgx** [comment]
您好，运行了您的代码，融合效果很好，想咨询一下您的内外参标定是怎么做的。谢谢

**Comment by GCaptainNemo** [comment]
> 您好，运行了您的代码，融合效果很好，想咨询一下您的内外参标定是怎么做的。谢谢

您可以参考我的仓库[Lidar-Camera-Calibration](https://github.com/GCaptainNemo/Lidar-Camera-Calibration),里面有我尝试的自动/手动标定方法。也可以用我开发的手动标定微调工具[Lidar-Camera-Calibration-Software](https://github.com/GCaptainNemo/Lidar-Camera-Calibration-Software)

**Comment by mikasazgx** [comment]
感谢分享
